### ISSUE TITLE
Battery Icon Issue

### ISSUE THREAD

**Issue by CathalButler** [L4ki/Cheerful-Phantasy-Themes#1]
Hi,

Big fan of the theme, I have really been enjoying it. I am jumping on here just to report an issue with the battery Icon, see:

![Screenshot_20201006_153545](https://user-images.githubusercontent.com/26792040/95216149-a449b380-07e9-11eb-8239-0e076b166443.png)

The cells inside the battery are vertical while the battery icon itself is horizontal.

**Comment by L4ki** [comment]
Hi CathalButler,

Thank you for this information.
I'm not using a laptop at the moment, so I can't check this icon (battery.svg).
I will update the Plasma Theme soon, so I will fix this bug.

Now I will put another battery.svg icon in the repositories, so you can download the Plasma Theme here, and install it manually.

If it's not a problem, let me know if it's okay now.

Best regards,

**Comment by L4ki** [comment]
Thank you for this information.
I'm not using a laptop at the moment, so I can't check this icon
(battery.svg).
I will update the Plasma Theme soon, so I will fix this bug.

Now I will put another battery.svg icon in the repositories, so you can
download the Plasma Theme here, and install it manually.

If it's not a problem, let me know if it's okay now.

Best regards,

**Comment by CathalButler** [comment]
I installed the theme manually and I am still suffering from the same issue as mentioned above I'm afraid.

**Comment by L4ki** [comment]
Hi CathalButler,

I changed the battery.svg icon again.
If it is not difficult for you, try to install again.
I don't know what could be the problem?
This icon I posted now should be fine.

Try clearing the cache.

**Comment by CathalButler** [comment]
The issue is now fixed with the updated icons/battery.svg.

Thank you!
